trigger:
  branches:
    include:
      - master
  paths:
    include:
      - backend/**
      - backend/**/*   # ensures even nested folder changes trigger the build

variables:
- group: edusync-variables
- name: buildConfiguration
  value: 'Release'
- name: buildPlatform
  value: 'Any CPU' # ensures the build is platform-agnostic

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
    - job: Build
      displayName: 'Build'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Restore'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'

        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'

        # - task: DotNetCoreCLI@2
        #   displayName: 'Test'
        #   inputs:
        #     command: 'test'
        #     projects: '**/*Tests/*.csproj'
        #     arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'

        - task: DotNetCoreCLI@2
          displayName: 'Publish'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
            zipAfterPublish: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifacts'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: Deploy
      displayName: 'Deploy to Azure App Service'
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureWebApp@1
                displayName: 'Deploy to Azure App Service'
                inputs:
                  azureSubscription: 'edusync-azure-connection'
                  appName: '$(WebAppName)'
                  package: '$(Pipeline.Workspace)/drop/*.zip'
                  deploymentMethod: 'auto'

              - task: AzureCLI@2
                displayName: 'Update App Service Configuration'
                inputs:
                  azureSubscription: 'edusync-azure-connection'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    az webapp config appsettings set --name $(WebAppName) --resource-group Edusync_Resources --settings \
                      ConnectionStrings__DefaultConnection="$(DatabaseConnectionString)" \
                      ASPNETCORE_ENVIRONMENT=Production \
                      WEBSITE_RUN_FROM_PACKAGE=1 \
                      ApplicationInsights__InstrumentationKey=$(AppInsightsKey) \
                      APPINSIGHTS_INSTRUMENTATIONKEY=$(AppInsightsKey)
